stages:
  load_data:
    cmd: python src\load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/winequality.csv
    outs:
    - data/raw/winequality.csv
  split_data:
    cmd: python src\split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/winequality.csv
    outs:
    - data/processed/train_winq.csv
    - data/processed/test_winq.csv
  tarin_eval:
    cmd: python src\train_and_eval.py --config=params.yaml
    deps:
    - src\train_and_eval.py
    - data/processed/train_winq.csv
    - data/processed/test_winq.csv
    params:
    - estimater.ElasticNet.params.alpha
    - estimater.ElasticNet.params.l1_ratio
    outs:
    - saved_models/model.joblib