base:
  prject: wineq
  randam_state: 13
  target_col: target

data_source:
  s3_source: data_given/winequality.csv

load_data:
  raw_dataset: data_given/winequality.csv

split_data:
  train_path: data/processed/train_winq.csv
  test_path: data/processed/test_winq.csv
  test_size: 0.2

estimater:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.4

model_dir:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib